### ISSUE TITLE
pre-trained model checkpoint

### ISSUE THREAD

**Issue by lemonbuilder** [Pangoraw/MarineMammalsDetection#1]
Thank you for sharing your research.
I'm trying to infer my custom dataset using your model.
Is it possible to use the weight of the pre-trained model?
I can't find any *.pth, *.ckpt files in your Git-hub.

If you could answer this questions, it would be really helpful!

**Comment by Pangoraw** [comment]
Hello,
Unfortunately, after looking back. I do not have any checkpoints accessible.
I may advise that you train a PaDiMshared model as a starting point: 

https://github.com/Pangoraw/PaDiM/blob/76f757fd51c46abda1ced5a26c2865c6d91a8cca/padim/padim_shared.py#L11

which is the most lightweight model proposed (fitting a single Gaussian).
